finalized firstboot

diff --git a/config/ansible/roles/firstboot/tasks/main.yml b/config/ansible/roles/firstboot/tasks/main.yml
--- a/config/ansible/roles/firstboot/tasks/main.yml
+++ b/config/ansible/roles/firstboot/tasks/main.yml
@@ -45,7 +45,7 @@
       sed -i 's/^\(session.*pam_env.so\)/\1\nsession    required   pam_mkhomedir.so     skel=\/etc\/skel umask=0077/' /etc/pam.d/system-login
     fi
 
-- name: Enable ntfs3 kernel support for read/write/repair of partitions
+- name: Enable ntfs3 kernel support for read/write/repair
   lineinfile:
     line: ntfs3
     path: /etc/modules-load.d/ntfs3.conf
@@ -219,3 +219,269 @@
 - name: Debian/Ubuntu
   include_tasks: apt-2.yml
   when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']
+
+- name: Generate random hostname once when no hostname is given
+  shell: |
+    if [ "x{{ setup_facts.setup.hostname }}" = "x" ]; then
+      tee /etc/hostname >/dev/null <<EOF
+    linux-$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 8).internal
+    EOF
+    else
+      tee /etc/hostname >/dev/null <<EOF
+    {{ setup_facts.setup.hostname }}
+    EOF
+    fi
+    hostnamectl hostname "$(</etc/hostname)"
+
+- name: Ensure journald.conf.d exists
+  file:
+    path: /etc/systemd/journald.conf.d
+    state: directory
+
+- name: Forward all logs to syslog-ng
+  copy:
+    dest: /etc/systemd/journald.conf.d/provision.conf
+    mode: 0644
+    content: |
+      [Journal]
+      # "Storage=none" means the systemd journal will drop all messages and "journalctl" will show no messages
+      #  -> "ForwardToSyslog=yes" is a must have
+      # With "Storage=volatile/auto" syslog-ng pulls in the messages from the systemd journal by default
+      #  -> "ForwardToSyslog=yes" means wasted system resources, duplicate log entries or additional errors
+      Storage=volatile
+      ForwardToSyslog=no
+
+- name: Log system() and internal() to local files
+  shell: |
+    sed -e '/^log.*};/d' -e '/^log/,/};/d' -e '/^options.*};/d' -e '/^options/,/};/d' -i /etc/syslog-ng/syslog-ng.conf
+    tee -a /etc/syslog-ng/syslog-ng.conf <<'EOF'
+    
+    options {
+      chain_hostnames(off);
+      keep_hostname(yes);
+      log_fifo_size(10000);
+      create_dirs(no);
+      flush_lines(0);
+      use_dns(no);
+      use_fqdn(no);
+      dns_cache(no);
+      owner(0);
+      group(0);
+      perm(0640);
+    EOF
+    if syslog-ng -V | head -n 1 | grep -q 'syslog-ng 3'; then
+      # ubuntu jammy has an old syslog-ng version
+      tee -a /etc/syslog-ng/syslog-ng.conf <<'EOF'
+      stats_freq(0);
+    EOF
+    else
+      # modern syntax
+      tee -a /etc/syslog-ng/syslog-ng.conf <<'EOF'
+      stats(freq(0));
+    EOF
+    fi
+    tee -a /etc/syslog-ng/syslog-ng.conf <<'EOF'
+      bad_hostname("^gconfd$");
+    };
+    
+    source s_prov_system {
+      system();
+      internal();
+    };
+    
+    destination d_prov_system {
+      file("/var/log/messages");
+      file("/var/log/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
+    };
+    
+    destination d_prov_auth {
+      file("/var/log/auth.log");
+    };
+    
+    destination d_prov_kern {
+      file("/var/log/kern.log");
+    };
+    
+    destination d_prov_user {
+      file("/var/log/user.log");
+    };
+    
+    filter f_prov_not_info {
+      not level(debug..info);
+    };
+    
+    filter f_prov_system {
+      filter(f_prov_not_info);
+    };
+    
+    filter f_prov_auth {
+      facility(auth, authpriv) and filter(f_prov_not_info);
+    };
+    
+    filter f_prov_kern {
+      facility(kern) and filter(f_prov_not_info);
+    };
+    
+    filter f_prov_user {
+      facility(user, daemon) and filter(f_prov_not_info);
+    };
+    
+    log {
+      source(s_prov_system);
+      filter(f_prov_system);
+      destination(d_prov_system);
+    };
+    
+    log {
+      source(s_prov_system);
+      filter(f_prov_auth);
+      destination(d_prov_auth);
+    };
+    
+    log {
+      source(s_prov_system);
+      filter(f_prov_kern);
+      destination(d_prov_kern);
+    };
+    
+    log {
+      source(s_prov_system);
+      filter(f_prov_user);
+      destination(d_prov_user);
+    };
+    EOF
+
+- name: Configure logrotate
+  shell: |
+    sed -i 's/^include/#include/g' /etc/logrotate.conf
+    tee -a /etc/logrotate.conf <<'EOF'
+    
+    # provisioned
+    /var/log/*.log /var/log/messages {
+        missingok
+        notifempty
+        daily
+        rotate 5
+        compress
+        delaycompress
+        maxage 21
+        size 50M
+        sharedscripts
+        postrotate
+            /bin/kill -HUP $(cat /run/syslog-ng.pid 2>/dev/null) 2>/dev/null || true
+        endscript
+    }
+    EOF
+
+- name: Prepare neovim
+  shell: |
+    mkdir -p /etc/skel/.local/share /etc/skel/.config/nvim
+    touch /etc/skel/.config/nvim/init.lua
+    ( HOME=/etc/skel /bin/bash -c 'nvim --headless -u "/etc/skel/.config/nvim/init.lua" -c ":lua require(\"nvim-treesitter.install\").update({ with_sync = true })" -c ":qall!" || true' ) &
+    pid=$!
+    wait $pid
+
+- name: Enabling btrfs root snapshots when not inside a container
+  shell: |
+    if findmnt -t btrfs -n /; then
+      echo "[ OK ] Detected btrfs root, enable daily/weekly/monthly snapshots"
+      snapper -c root create-config /
+      sed -i 's/TIMELINE_MIN_AGE=.*/TIMELINE_MIN_AGE="1800"/' /etc/snapper/configs/root
+      sed -i 's/TIMELINE_LIMIT_HOURLY=.*/TIMELINE_LIMIT_HOURLY="0"/' /etc/snapper/configs/root
+      sed -i 's/TIMELINE_LIMIT_DAILY=.*/TIMELINE_LIMIT_DAILY="2"/' /etc/snapper/configs/root
+      sed -i 's/TIMELINE_LIMIT_WEEKLY=.*/TIMELINE_LIMIT_WEEKLY="2"/' /etc/snapper/configs/root
+      sed -i 's/TIMELINE_LIMIT_MONTHLY=.*/TIMELINE_LIMIT_MONTHLY="1"/' /etc/snapper/configs/root
+      sed -i 's/TIMELINE_LIMIT_YEARLY=.*/TIMELINE_LIMIT_YEARLY="0"/' /etc/snapper/configs/root
+      mkdir -p /etc/systemd/system/snapper-{backup,boot,timeline,cleanup}{.timer.d,.service.d}
+      tee /etc/systemd/system/snapper-{backup,boot,timeline,cleanup}{.timer.d,.service.d}/override.conf <<EOF
+    [Unit]
+    ConditionVirtualization=
+    ConditionVirtualization=!container
+    EOF
+      systemctl enable snapper-timeline.timer snapper-cleanup.timer
+    else
+      echo "[FAIL] No btrfs root detected, no snapshots will be available"
+      systemctl disable snapper-timeline.timer snapper-cleanup.timer
+    fi
+
+- name: Configure ufw
+  shell: |
+    ufw disable
+    # clear default ruleset
+    LC_ALL=C yes | LC_ALL=C ufw reset
+    for i in $(seq -- 10 -1 1)
+    do
+      LC_ALL=C yes | LC_ALL=C ufw delete "$i" 2>/dev/null
+    done
+    # logs all blocked packets and packets matching logged rules
+    ufw logging low
+    # outgoing is always allowed, incoming and routed should be denied
+    ufw default deny incoming
+    ufw default deny routed
+    ufw default allow outgoing
+    # ssh access on all devices
+    ufw allow log ssh comment 'allow ssh'
+    # cockpit access on all devices
+    ufw allow log 9090/tcp comment 'allow cockpit'
+    # allow mdns
+    ufw allow mdns comment 'allow mdns'
+    # disable UPnP (keeping the rules for mDNS)
+    sed -i 's/^\(.*--dport 1900.*\)/#\1/' /etc/ufw/before.rules
+    sed -i 's/^\(.*--dport 1900.*\)/#\1/' /etc/ufw/before6.rules
+
+- name: Enable ufw on next boot
+  lineinfile:
+    regexp: '^ENABLED='
+    line: ENABLED=yes
+    path: /etc/ufw/ufw.conf
+    state: present
+
+- name: Remove cockpit messages on startup
+  shell: |
+    ln -sfn /dev/null /etc/motd.d/cockpit
+    ln -sfn /dev/null /etc/issue.d/cockpit.issue
+
+- name: Enable mDNS
+  shell: |
+    systemctl stop avahi-daemon{.service,.socket}
+    systemctl disable avahi-daemon{.service,.socket}
+    systemctl mask avahi-daemon{.service,.socket}
+    sed -e 's/^#\?MulticastDNS.*/MulticastDNS=yes/' -e 's/^#\?LLMNR.*/LLMNR=no/' -i /etc/systemd/resolved.conf
+    [ -d /etc/NetworkManager/conf.d ] && tee -a /etc/NetworkManager/conf.d/globals.conf <<EOF
+    [connection]
+    connection.mdns=2
+    connection.llmnr=0
+    [main]
+    dns=none
+    rc-manager=unmanaged
+    EOF
+    # debian 13 hack
+    mkdir -p /etc/systemd/resolved.conf.d
+    ln -s /dev/null /etc/systemd/resolved.conf.d/00-disable-mdns.conf
+
+- name: Enable default mDNS advertising
+  shell: |
+    mkdir -p /etc/systemd/dnssd
+    tee /etc/systemd/dnssd/ssh.dnssd <<EOF
+    [Service]
+    Name=%H
+    Type=_ssh._tcp
+    Port=22
+    EOF
+    tee /etc/systemd/dnssd/cockpit.dnssd <<EOF
+    [Service]
+    Name=%H
+    Type=_cockpit._tcp
+    Port=9090
+    EOF
+
+- name: Apply skeleton to all users
+  shell: |
+    getent passwd | while IFS=: read -r username x uid gid gecos home shell; do
+      if [ -n "$home" ] && [ -d "$home" ] && [ "$home" != "/" ]; then
+        if [ "$uid" -eq 0 ] || [ "$uid" -ge 1000 ]; then
+          echo ":: apply skeleton to $home [$username $uid:$gid]"
+          rsync -a --chown=$uid:$gid /etc/skel/ "$home"
+        fi
+      fi
+    done
