refactor pxe http bootcode

diff --git a/config/pxe/90_pxe_image/hooks/pxe_http b/config/pxe/90_pxe_image/hooks/pxe_http
--- a/config/pxe/90_pxe_image/hooks/pxe_http
+++ b/config/pxe/90_pxe_image/hooks/pxe_http
@@ -30,18 +30,11 @@ pxe_http_mount_handler() {
     # 2nd: download the image
     msg ":: Download '${http_img}' to '${local_img}'"
     mkdir -p "${local_img%/pxeboot.img}"
-    if command -v wget >/dev/null 2>&1; then
-        if ! wget -c -N -O "${local_img}" --progress=dot:giga "${http_img}"; then
-            echo "!! ERROR: could not download '${http_img}' to '${local_img}'"
-            launch_interactive_shell
-        fi
-    else
-        if ! curl -L -f -o "${local_img}" "${http_img}"; then
-            echo "!! ERROR: could not download '${http_img}' to '${local_img}'"
-            launch_interactive_shell
-        fi
+    if ! wget -c -O "${local_img}" "${http_img}"; then
+        echo "!! ERROR: could not download '${http_img}' to '${local_img}'"
+        launch_interactive_shell
     fi
-
+    
     # 3rd: create the boot mount point for pxe_mount_handler with correct image placement
     msg ":: Bindmount '${copytoram_mnt}' as '${boot_mnt}'"
     if ! mount --mkdir -o bind "${copytoram_mnt}" "${boot_mnt}"; then
